name: Docker Image CI

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Build Productpage
      run: |     
        docker build -t productpage:meetup $GITHUB_WORKSPACE/src/productpage
    - name: Setup k8s cluster
      uses: engineerd/setup-kind@v0.1.0
    - name: Load Productpage
      run: |     
        kind load docker-image productpage:meetup
        kubectl create deployment productpage --image=productpage:meetup --dry-run -o yaml | kubectl apply -f -
        

# kind load docker-image productpage:$sha      
#    sha=${GITHUB_SHA:0:7}
#         app="${GITHUB_REPOSITORY#*/}"
