name: Docker Image CI

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Build Productpage
      run: |     
        sha=${GITHUB_SHA:0:7}
        docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/productpage:$sha $GITHUB_WORKSPACE/src/productpage
        docker login docker.pkg.github.com -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/productpage:$sha
#     - name: Setup k8s cluster
#       uses: engineerd/setup-kind@v0.1.0
#     - name: Load Productpage
#       run: |     
#         kind load docker-image productpage:meetup
#         kubectl create deployment productpage --image=productpage:meetup --dry-run -o yaml | kubectl apply -f -
      

# kind load docker-image productpage:$sha      
#    sha=${GITHUB_SHA:0:7}
#         app="${GITHUB_REPOSITORY#*/}"
# docker build -t productpage:$sha $GITHUB_WORKSPACE/src/productpage
